FROM ubuntu:18.04

ADD . .

RUN apt-get update -y
RUN apt-get install wget curl git sudo gnupg2 software-properties-common -y


SHELL ["/bin/bash", "-c"]
RUN source setup.sh
RUN wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | sudo apt-key add -
RUN apt-get update -y

RUN apt-get install linux-headers-$(uname -r) -y
RUN apt-get install aws-neuronx-dkms -y
RUN apt-get install aws-neuronx-tools -y
# # RUN apt-get install aws-neuronx-runtime-lib -y


ENV PATH=/opt/aws/neuron/bin:$PATH


## python 3.7설치
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get install -y python3.7 python3.7-dev python3.7-distutils apt-transport-https g++ protobuf-compiler 
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py 
RUN python3.7 get-pip.py 
RUN ln -s /usr/bin/python3.7 /usr/bin/python


## aws 뉴런 sdk python 패키지 설치 ( 파이썬까지 자동으로 설치됨)
RUN pip config set global.extra-index-url "https://pip.repos.neuron.amazonaws.com"
RUN pip install "torch-neuron==1.8.1.*" "neuron-cc[tensorflow]" "protobuf==3.20.1" torchvision numpy
RUN pip install prometheus_client python-multipart fastapi uvicorn[standard]